const express = require('express')
const estudanteController = require('./../controllers/estudanteController')
const authController = require('./../controllers/authController')
const router = express.Router()
router.use(authController.protect)
router.post('/cadastrar', estudanteController.cadastrarEstudante)
router.post('/inscrever', estudanteController.inscreverEstudante)
router.get('/validateInscript/:id', estudanteController.setValid)
router.post('/getCaderneta', estudanteController.Caderneta)
router.get('/getOne', estudanteController.getStudent)
router.get('/inscript', estudanteController.getStudent)
router.get('/getAll', estudanteController.getStudents)
router.get('/getList', estudanteController.getList)
router.patch('/updateStudent/:id', estudanteController.updateStudent)
module.exports = router